# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressOne', models.CharField(max_length=80)),
                ('colonia', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=18)),
                ('businessName', models.CharField(blank=True, max_length=20)),
                ('images', models.FileField(upload_to='/uploads')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='Usuarios.Address')),
            ],
        ),
    ]
