# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
