# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_infouser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='address',
        ),
    ]
