# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_infouser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='Usuarios.Address'),
        ),
    ]
