# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_auto_20161213_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='images',
            field=models.FileField(blank=True, upload_to='/uploads'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='telephone',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
