# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0003_auto_20161210_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='vendedor',
        ),
    ]
