# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventarios', '0004_remove_producto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producto_vendedor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
